### PR TITLE
Update tests to use Firefox and latest deps

### PR DESCRIPTION
**Pull request by ijdickinson**
General updates to use Firefox as the browser, and webdrivers as the
browser driver library. Some minor test changes as a consequence.

@bwmcbride Can you please test these changes to ensure that they run OK on your machine? I note that one of the tests is failing due to data selection: in `common stop words not stopped`, there are no properties with `The` in the title in the latest month's data. Manually testing with the date range set to a longer period does produce data, so I think the test is giving a false negative.

At the moment I've simply made Firefox the default browser, but we could easily make that a command-line argument if you prefer?

### CODE REVIEW

**Comment by ijdickinson** [comment]
@andrew-pickin-epi What value would you like to test against for `TEST_BROWSER_VISIBLE`? I guess my opening gambit would be that the browser window is visible iff `$TEST_BROWSER_VISIBLE == 1`. Or would you prefer to see a more explicit value like `$TEST_BROWSER_VISIBLE == "visible"`?

**Comment by ijdickinson** [comment]
@bwmcbride @andrew-pickin-epi Suggest we merge this branch first, once you're happy with it, which will make it easier to clearly see the changes in the other candidate branches

**Comment by bwmcbride** [comment]
I would like to keep the master branch in a state that works for me so I would prefer the firefox switch and the container update to go onto master at the same time.

Contrary to Andy's assertion that the tests in master are broken - they work for me because I have the required version of chrome installed.

I tried running tests in the firefix feature branch and they fail on my machine.   So rather than mess with my dev box with other potential side effects I set up the container to run the tests.

**Comment by andrew-pickin-epi** [comment]
> I would like to keep the master branch in a state that works for me so I would prefer the firefox switch and the container update to go onto master at the same time.
> 
> Contrary to Andy's assertion that the tests in master are broken - they work for me because I have the required version of chrome installed.
> 
> I tried running tests in the firefix feature branch and they fail on my machine. So rather than mess with my dev box with other potential side effects I set up the container to run the tests.

That's fine for you. But that environment is no longer practicable. I can't install it.

**Comment by andrew-pickin-epi** [comment]
> @andrew-pickin-epi What value would you like to test against for `TEST_BROWSER_VISIBLE`? I guess my opening gambit would be that the browser window is visible iff `$TEST_BROWSER_VISIBLE == 1`. Or would you prefer to see a more explicit value like `$TEST_BROWSER_VISIBLE == "visible"`?

I don't really mind. I just fear there is scope for ambiguity. As TEST_BROWSER_VISIBLE="" counts a "set" as to unset an env var is to undefine it. So ideally true(ie visible) would be when defined and non-zero length an value. Although this does allow for TEST_BROWSER="false" to be true I can like with that. If you want to insist on "1" that's fine too.

**Comment by bwmcbride** [comment]
These tests working for me (and master branch now doesn't).

I have made some tweaks to some cucumber tests to address introduce delays to address some failing tests.

**Pull request merged**
